apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: si-contract
  labels:
    app.kubernetes.io/name: app-secrets
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: si-contract
type: Opaque
stringData:
  DATABASE_URL: "postgresql://dbadmin:H=7XwfHbVVuQ[-hChVWq3{Vxy2ifD6_f@si-contract-dev-aurora.cluster-cvjd41jr4fzh.ap-northeast-2.rds.amazonaws.com:5432/si_contract"
