apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: si-contract
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: si-contract
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
